name = "All of Ori-rinth"
author = "Munsterlandr"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51236b5d67b47358e88972b1e466ed003263d9dc564b14d6b7751ac7304cedd5"

[versions]
minecraft = "1.19.3"
quilt = "0.19.0-beta.13"
