name = "All of Ori-rinth"
author = "Munsterlandr"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "222a50f7cc749ab557fa4823beb350d9591dfd3f3c027e51b07b689ce99a8e56"

[versions]
minecraft = "1.19.3"
quilt = "0.19.0-beta.13"
